-- ASHUR 1.2 platform expansion
-- Applied to project pwpjrwcynnicexrmunkd on 2026-09-28.
-- This file is intentionally additive/backward-compatible.

alter table public.profiles
  add column if not exists banned_until timestamptz,
  add column if not exists ban_reason text not null default '',
  add column if not exists warning_count integer not null default 0,
  add column if not exists last_seen_at timestamptz,
  add column if not exists deleted_at timestamptz;

alter table public.posts
  add column if not exists moderation_status text not null default 'active',
  add column if not exists deleted_at timestamptz,
  add column if not exists hidden_by uuid references auth.users(id) on delete set null,
  add column if not exists visibility text not null default 'public';

alter table public.reels
  add column if not exists moderation_status text not null default 'active',
  add column if not exists deleted_at timestamptz,
  add column if not exists hidden_by uuid references auth.users(id) on delete set null,
  add column if not exists visibility text not null default 'public';

alter table public.stories
  add column if not exists moderation_status text not null default 'active',
  add column if not exists deleted_at timestamptz,
  add column if not exists hidden_by uuid references auth.users(id) on delete set null;

alter table public.comments
  add column if not exists moderation_status text not null default 'active',
  add column if not exists deleted_at timestamptz,
  add column if not exists hidden_by uuid references auth.users(id) on delete set null;

alter table public.reports
  add column if not exists admin_note text not null default '',
  add column if not exists handled_by uuid references auth.users(id) on delete set null,
  add column if not exists action_taken text not null default '',
  add column if not exists updated_at timestamptz not null default now();

alter table public.admins
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_active_at timestamptz;

create table if not exists public.saved_reels (
  user_id uuid not null references auth.users(id) on delete cascade,
  reel_id uuid not null references public.reels(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, reel_id)
);

create table if not exists public.story_views (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (story_id, user_id)
);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'general',
  subject text not null default '',
  body text not null default '',
  status text not null default 'open',
  priority text not null default 'normal',
  admin_reply text not null default '',
  assigned_to uuid references auth.users(id) on delete set null,
  app_version text not null default '',
  device_info text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.upload_jobs (
  id uuid primary key default gen_random_uuid(),
  client_upload_id text unique,
  user_id uuid references auth.users(id) on delete set null,
  kind text not null,
  original_name text not null default '',
  size_bytes bigint not null default 0,
  received_bytes bigint not null default 0,
  status text not null default 'queued',
  error text,
  media_id uuid references public.media_objects(id) on delete set null,
  cancel_requested boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.system_errors (
  id bigint generated by default as identity primary key,
  service text not null,
  code text not null default '',
  message text not null,
  context jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.admin_notification_history (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid references auth.users(id) on delete set null,
  title text not null,
  body text not null,
  audience text not null default 'all',
  target_user_id uuid references auth.users(id) on delete set null,
  deep_link jsonb not null default '{}'::jsonb,
  scheduled_at timestamptz,
  sent_at timestamptz,
  status text not null default 'pending',
  push_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.app_releases (
  id uuid primary key default gen_random_uuid(),
  version text not null,
  version_code integer not null,
  download_url text not null default '',
  notes text not null default '',
  required boolean not null default false,
  minimum_version text not null default '',
  status text not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique(version, version_code)
);

create index if not exists saved_reels_reel_user_idx on public.saved_reels(reel_id,user_id);
create index if not exists story_views_story_viewed_idx on public.story_views(story_id,viewed_at desc);
create index if not exists support_tickets_user_created_idx on public.support_tickets(user_id,created_at desc);
create index if not exists support_tickets_status_created_idx on public.support_tickets(status,created_at desc);
create index if not exists upload_jobs_status_created_idx on public.upload_jobs(status,created_at desc);
create index if not exists upload_jobs_user_created_idx on public.upload_jobs(user_id,created_at desc);
create index if not exists system_errors_status_created_idx on public.system_errors(status,created_at desc);
create index if not exists admin_notification_history_created_idx on public.admin_notification_history(created_at desc);
create index if not exists app_releases_created_idx on public.app_releases(created_at desc);
create index if not exists profiles_banned_until_idx on public.profiles(banned_until) where banned_until is not null;
create index if not exists reports_status_created_idx on public.reports(status,created_at desc);
create index if not exists comments_parent_created_idx on public.comments(parent_id,created_at) where parent_id is not null;

alter table public.saved_reels enable row level security;
alter table public.story_views enable row level security;
alter table public.support_tickets enable row level security;
alter table public.upload_jobs enable row level security;
alter table public.system_errors enable row level security;
alter table public.admin_notification_history enable row level security;
alter table public.app_releases enable row level security;

drop policy if exists saved_reels_own on public.saved_reels;
create policy saved_reels_own on public.saved_reels
for all to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists story_views_read on public.story_views;
create policy story_views_read on public.story_views
for select to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.stories s
    where s.id = story_views.story_id
      and s.author_id = (select auth.uid())
  )
);

drop policy if exists story_views_insert on public.story_views;
create policy story_views_insert on public.story_views
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (select 1 from public.stories s where s.id = story_views.story_id)
);

drop policy if exists support_tickets_own_read on public.support_tickets;
create policy support_tickets_own_read on public.support_tickets
for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists support_tickets_own_insert on public.support_tickets;
create policy support_tickets_own_insert on public.support_tickets
for insert to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists message_reads_member on public.message_reads;
create policy message_reads_member on public.message_reads
for select to authenticated
using (
  exists (
    select 1
    from public.messages m
    where m.id = message_reads.message_id
      and private.is_conversation_member(m.conversation_id)
  )
);
